add types
shystruk/csv-file-validator pull request #68
Opened 2021-07-08 09:38 UTC by javierlinked

2021-07-08 09:41 UTC, shystruk commented
Hi @javierlinked 
Can you please add a demo page with .ts where we can test that the package works.
You can add a new .html page to **demo** folder or create a new **demo-ts** folder :) 
Thanks

2021-08-04 09:33 UTC, javierlinked commented
Hello @shystruk. Done :D

2021-08-04 21:43 UTC, shystruk requested changes

2021-08-04 21:43 UTC, shystruk commented on demo-ts/index.js
> +import CSVFileValidator from '../src/csv-file-validator'
@javierlinked Can you please create the index.ts file and make sure you import .ts  module to make sure type definitions work well.

2021-08-20 04:41 UTC, shystruk commented
@javierlinked thank you for the contribution. In #79 type definitions were added.

2021-08-20 04:41 UTC, closed without merging